//-------------------------------------------------------------------
// <auto-generated>
// 此代码由T4模板自动生成
// 生成时间 2016-03-08 00:31:29 by stwhh
// 对此文件的更改可能会导致不正确的行为，如果
// 重新生成代码，这些更改将会丢失。
// </auto-generated>
//-------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace CoolPlugins.Public.Entities
{    
    public class AskForLeave
    {
                
		/// <summary>
        /// 
        /// </summary>        
        public int ID { get; set; }
                
		/// <summary>
        /// 请假编号
        /// </summary>        
        public string AskForLeaveCode { get; set; }
                
		/// <summary>
        /// 申请日期
        /// </summary>        
        public DateTime ApplyDate { get; set; }
                
		/// <summary>
        /// 开始日期
        /// </summary>        
        public DateTime BeginDate { get; set; }
                
		/// <summary>
        /// 结束日期
        /// </summary>        
        public DateTime EndDate { get; set; }
                
		/// <summary>
        /// 请假类型
        /// </summary>        
        public int TypeId { get; set; }
                
		/// <summary>
        /// 请假原因
        /// </summary>        
        public string Reason { get; set; }
                
		/// <summary>
        /// 审核时间
        /// </summary>        
        public DateTime? ApprovalTime { get; set; }
                
		/// <summary>
        /// 
        /// </summary>        
        public string Status { get; set; }
                
		/// <summary>
        /// 请假用户编号
        /// </summary>        
        public string UserCode { get; set; }
                
		/// <summary>
        /// 创建时间
        /// </summary>        
        public DateTime? CreateTime { get; set; }
                
		/// <summary>
        /// 创建者编号
        /// </summary>        
        public string CreateUserCode { get; set; }
                
		/// <summary>
        /// 修改时间
        /// </summary>        
        public DateTime? ModifyTime { get; set; }
                
		/// <summary>
        /// 修改者编号
        /// </summary>        
        public string ModifyUserCode { get; set; }
                
		/// <summary>
        /// 预留1
        /// </summary>        
        public string Addtion1 { get; set; }
                
		/// <summary>
        /// 预留2
        /// </summary>        
        public string Addtion2 { get; set; }
         
    }
}
