
//-------------------------------------------------------------------
// <auto-generated>
// 此代码由T4模板自动生成
// 生成时间 2016-04-10 21:30:42 by stwhh
// 对此文件的更改可能会导致不正确的行为，如果
// 重新生成代码，这些更改将会丢失。
// </auto-generated>
//-------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Configuration;

namespace CoolPlugins.Public.Entities
{    
    public class Project_Discuss : ITableBase<Project_Discuss>
    {
		public string TableName="Project_Discuss"; //表名
		/// <summary>
        /// 获取表名
        /// </summary>     
		public string GetTableName()
		{
			return TableName ;
		}
        
         
		public string PrimaryKey="ID"; //主键
		/// <summary>
        /// 获取主键
        /// </summary>     
		public string GetPrimaryKey()
		{
			return PrimaryKey ;
		} 
		/// <summary>
        /// 
        /// </summary>        
        public int ID { get; set; }
        
         
		/// <summary>
        /// 
        /// </summary>        
        public string ProjCode { get; set; }
        
         
		/// <summary>
        /// 项目讨论内容
        /// </summary>        
        public string ProjComConent { get; set; }
        
         
		/// <summary>
        /// 
        /// </summary>        
        public DateTime CreateTime { get; set; }
        
         
		/// <summary>
        /// 
        /// </summary>        
        public string CreateUserCode { get; set; }
        
         
		/// <summary>
        /// 
        /// </summary>        
        public string CreateUserImage { get; set; }
        
         
		/// <summary>
        /// 预留1
        /// </summary>        
        public string Addtion1 { get; set; }
        
         
		/// <summary>
        /// 预留2
        /// </summary>        
        public string Addtion2 { get; set; }
         
    }
}

