
//-------------------------------------------------------------------
// <auto-generated>
// 此代码由T4模板自动生成
// 生成时间 2016-04-10 21:30:42 by stwhh
// 对此文件的更改可能会导致不正确的行为，如果
// 重新生成代码，这些更改将会丢失。
// </auto-generated>
//-------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Configuration;

namespace CoolPlugins.Public.Entities
{    
    public class Reim : ITableBase<Reim>
    {
		public string TableName="Reim"; //表名
		/// <summary>
        /// 获取表名
        /// </summary>     
		public string GetTableName()
		{
			return TableName ;
		}
        
         
		public string PrimaryKey="ID"; //主键
		/// <summary>
        /// 获取主键
        /// </summary>     
		public string GetPrimaryKey()
		{
			return PrimaryKey ;
		} 
		/// <summary>
        /// 
        /// </summary>        
        public int ID { get; set; }
        
         
		/// <summary>
        /// 报销单号
        /// </summary>        
        public string ReimCode { get; set; }
        
         
		/// <summary>
        /// 报销内容
        /// </summary>        
        public string ReimContent { get; set; }
        
         
		/// <summary>
        /// 
        /// </summary>        
        public DateTime ApplyDate { get; set; }
        
         
		/// <summary>
        /// 机票
        /// </summary>        
        public string AirTicket { get; set; }
        
         
		/// <summary>
        /// 火车(高铁)
        /// </summary>        
        public string Train { get; set; }
        
         
		/// <summary>
        /// 客车
        /// </summary>        
        public string Bus { get; set; }
        
         
		/// <summary>
        /// 室内交通费
        /// </summary>        
        public string Traffic { get; set; }
        
         
		/// <summary>
        /// 住宿费
        /// </summary>        
        public string Accommodation { get; set; }
        
         
		/// <summary>
        /// 出差补贴
        /// </summary>        
        public string Bonus { get; set; }
        
         
		/// <summary>
        /// 
        /// </summary>        
        public string Other { get; set; }
        
         
		/// <summary>
        /// 报销费用
        /// </summary>        
        public string ReimMoney { get; set; }
        
         
		/// <summary>
        /// 
        /// </summary>        
        public string UserCode { get; set; }
        
         
		/// <summary>
        /// 出差单号
        /// </summary>        
        public string TripCode { get; set; }
        
         
		/// <summary>
        /// 
        /// </summary>        
        public string Status { get; set; }
        
         
		/// <summary>
        /// 创建时间
        /// </summary>        
        public DateTime? CreateTime { get; set; }
        
         
		/// <summary>
        /// 创建者编号
        /// </summary>        
        public string CreateUserCode { get; set; }
        
         
		/// <summary>
        /// 修改时间
        /// </summary>        
        public DateTime? ModifyTime { get; set; }
        
         
		/// <summary>
        /// 修改者编号
        /// </summary>        
        public string ModifyUserCode { get; set; }
        
         
		/// <summary>
        /// 预留1
        /// </summary>        
        public string Addtion1 { get; set; }
        
         
		/// <summary>
        /// 预留2
        /// </summary>        
        public string Addtion2 { get; set; }
         
    }
}

