//-------------------------------------------------------------------
// <auto-generated>
// 此代码由T4模板自动生成
// 生成时间 2016-03-08 00:31:29 by stwhh
// 对此文件的更改可能会导致不正确的行为，如果
// 重新生成代码，这些更改将会丢失。
// </auto-generated>
//-------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace CoolPlugins.Public.Entities
{    
    public class Role_Permisson
    {
                
		/// <summary>
        /// 
        /// </summary>        
        public int ID { get; set; }
                
		/// <summary>
        /// 
        /// </summary>        
        public string RoleCode { get; set; }
                
		/// <summary>
        /// 
        /// </summary>        
        public string PermCode { get; set; }
                
		/// <summary>
        /// 创建时间
        /// </summary>        
        public DateTime? CreateTime { get; set; }
                
		/// <summary>
        /// 创建者编号
        /// </summary>        
        public string CreateUserCode { get; set; }
                
		/// <summary>
        /// 修改时间
        /// </summary>        
        public DateTime? ModifyTime { get; set; }
                
		/// <summary>
        /// 修改者编号
        /// </summary>        
        public string ModifyUserCode { get; set; }
                
		/// <summary>
        /// 预留1
        /// </summary>        
        public string Addtion1 { get; set; }
                
		/// <summary>
        /// 预留2
        /// </summary>        
        public string Addtion2 { get; set; }
         
    }
}
