//-------------------------------------------------------------------
// <auto-generated>
// 此代码由T4模板自动生成
// 生成时间 2016-03-08 00:31:29 by stwhh
// 对此文件的更改可能会导致不正确的行为，如果
// 重新生成代码，这些更改将会丢失。
// </auto-generated>
//-------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace CoolPlugins.Public.Entities
{    
    public class sysdiagrams
    {
                
		/// <summary>
        /// 
        /// </summary>        
        public object name { get; set; }
                
		/// <summary>
        /// 
        /// </summary>        
        public int principal_id { get; set; }
                
		/// <summary>
        /// 
        /// </summary>        
        public int diagram_id { get; set; }
                
		/// <summary>
        /// 
        /// </summary>        
        public int? version { get; set; }
                
		/// <summary>
        /// 
        /// </summary>        
        public byte[] definition { get; set; }
         
    }
}
