
//-------------------------------------------------------------------
// <auto-generated>
// 此代码由T4模板自动生成
// 生成时间 2016-04-10 21:30:42 by stwhh
// 对此文件的更改可能会导致不正确的行为，如果
// 重新生成代码，这些更改将会丢失。
// </auto-generated>
//-------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Configuration;

namespace CoolPlugins.Public.Entities
{    
    public class sysdiagrams : ITableBase<sysdiagrams>
    {
		public string TableName="sysdiagrams"; //表名
		/// <summary>
        /// 获取表名
        /// </summary>     
		public string GetTableName()
		{
			return TableName ;
		}
        
         
		/// <summary>
        /// 
        /// </summary>        
        public object name { get; set; }
        
         
		/// <summary>
        /// 
        /// </summary>        
        public int principal_id { get; set; }
        
         
		public string PrimaryKey="diagram_id"; //主键
		/// <summary>
        /// 获取主键
        /// </summary>     
		public string GetPrimaryKey()
		{
			return PrimaryKey ;
		} 
		/// <summary>
        /// 
        /// </summary>        
        public int diagram_id { get; set; }
        
         
		/// <summary>
        /// 
        /// </summary>        
        public int? version { get; set; }
        
         
		/// <summary>
        /// 
        /// </summary>        
        public byte[] definition { get; set; }
         
    }
}

