//-------------------------------------------------------------------
// <auto-generated>
// 此代码由T4模板自动生成
// 生成时间 2016-03-08 00:31:29 by stwhh
// 对此文件的更改可能会导致不正确的行为，如果
// 重新生成代码，这些更改将会丢失。
// </auto-generated>
//-------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace CoolPlugins.Public.Entities
{    
    public class User
    {
                
		/// <summary>
        /// 
        /// </summary>        
        public int ID { get; set; }
                
		/// <summary>
        /// 用户名
        /// </summary>        
        public string UserCode { get; set; }
                
		/// <summary>
        /// 真实姓名
        /// </summary>        
        public string RealName { get; set; }
                
		/// <summary>
        /// 用户密码
        /// </summary>        
        public string UserPwd { get; set; }
                
		/// <summary>
        /// 用户性别
        /// </summary>        
        public string Sex { get; set; }
                
		/// <summary>
        /// 用户年龄
        /// </summary>        
        public int Age { get; set; }
                
		/// <summary>
        /// 用户电话
        /// </summary>        
        public string Phone { get; set; }
                
		/// <summary>
        /// 用户QQ
        /// </summary>        
        public string QQ { get; set; }
                
		/// <summary>
        /// 用户邮箱
        /// </summary>        
        public string Email { get; set; }
                
		/// <summary>
        /// 用户地址
        /// </summary>        
        public string Address { get; set; }
                
		/// <summary>
        /// 用户入职时间
        /// </summary>        
        public DateTime EntryDate { get; set; }
                
		/// <summary>
        /// 职位编号
        /// </summary>        
        public string PositionCode { get; set; }
                
		/// <summary>
        /// 部门编号
        /// </summary>        
        public string DepartmentCode { get; set; }
                
		/// <summary>
        /// 创建时间
        /// </summary>        
        public DateTime? CreateTime { get; set; }
                
		/// <summary>
        /// 创建者编号
        /// </summary>        
        public string CreateUserCode { get; set; }
                
		/// <summary>
        /// 修改时间
        /// </summary>        
        public DateTime? ModifyTime { get; set; }
                
		/// <summary>
        /// 修改者编号
        /// </summary>        
        public string ModifyUserCode { get; set; }
                
		/// <summary>
        /// 预留1
        /// </summary>        
        public string Addtion1 { get; set; }
                
		/// <summary>
        /// 预留2
        /// </summary>        
        public string Addtion2 { get; set; }
         
    }
}
